# Docker Compose for local development only (no app container)
version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: aipocket_postgres_dev
    environment:
      POSTGRES_DB: aipocket_local
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_dev_data: