name: Deploy to GKE

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}

jobs:
  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      
    - name: Configure kubectl
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $PROJECT_ID
        
    - name: Build and deploy with Cloud Build
      run: |
        gcloud builds submit \
          --config cloudbuild.yaml \
          --substitutions _CLOUDSDK_COMPUTE_ZONE="$GKE_ZONE",_CLOUDSDK_CONTAINER_CLUSTER="$GKE_CLUSTER",PROJECT_ID="$PROJECT_ID" \
          --project $PROJECT_ID
